language: node_js
node_js:
    - "0.10"

install:
    - "npm install karma"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
    - "npm test"

notifications:
    email: false
    irc:
        channels:
            - "frogbox.es#DesktopCS"
        skip_join: true
